#Get all user info
GET http://localhost:8080/users

### Second Request
POST http://localhost:8080/users/createUser
Content-Type: application/json

//

{
    "username": "BUTCHER",
    "hashed_password": "cunt",
    "email": "mmilk@gmail.com"
}
###EXAMPLE DELETE REQUEST
POST http://localhost:8080/users/deleteUser
Content-Type: application/json

{
    "_id": "669d7cc33208534b77225ba3"
}


###Login Request
POST http://localhost:8080/users/login
Content-Type: application/json

{
    "username": "BUTCHER",
    "hashed_password": "cunt"
}

###Example of using token to access webpage stuff
GET http://localhost:8080/users/getUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjllZjZiNGJmNGJmMjFmZWNhNTUyM2UiLCJ1c2VybmFtZSI6IkJVVENIRVIiLCJpYXQiOjE3MjE3NTIxODZ9.OQzvVY2k1rzejVBTHDqgfnO1JS9cDp7uXkBFdwH20KE